language: python
python:
- "3.5"

cache: pip

install:
  - pip install -U pip wheel
  - pip install tox
script:
  - travis_retry tox -e $TOX_ENV

env:
  fast_finish: true
  global:
    - DATABASE_URL="mysql://root:@localhost/petycja_norweskie"
  matrix:
    - TOX_ENV=dj110-coveralls
    - TOX_ENV=dj111-coveralls
    - TOX_ENV=djmaster-coveralls
matrix:
  allow_failures:
    - env: TOX_ENV=djmaster-coveralls
