---
- hosts: all
  vars:
    db_name: petycja_norweskie
    db_user: petycja_norweskie
    db_pass: petycja_norweskie
    db_names:
      - "{{ db_name }}"
      - "test-{{ db_name }}"
    env_path: "~/env"
    src_path: "/vagrant"
    requirements_path: "{{src_path}}/requirements/local.txt"
    virtualenv_python: /usr/bin/python3.5
    settings: {
      DJANGO_SETTINGS_MODULE: "config.settings.local",
      DATABASE_URL: "mysql://{{db_user}}:{{db_pass}}@localhost/{{db_name}}"
    }
  tasks:
  - name: Add repository key to the system
    apt_key: keyserver=keyserver.ubuntu.com id=0xF1656F24C74CD1D8
    register: repository_status
    become: yes

  - name: Install MariaDB repository
    apt_repository:
      repo: 'deb [arch=amd64,i386,ppc64el] http://mariadb.kisiek.net/repo/10.1/ubuntu xenial main'
      state: present
    become: yes

  - name: Update repository info
    # Workaround of https://github.com/ansible/ansible/issues/21006
    apt:
      update_cache: yes
    when: repository_status.changed
    become: yes

  - name: Install OS-level libraries and application
    apt:
      name: "{{item}}"
      state: latest
    with_items:
      - git
      - build-essential
      - python3.5
      - python-virtualenv
      - python3-virtualenv
      - python3.5-dev
      - mariadb-server
      - python-pip
      - libmariadbclient18
      - libmariadbclient-dev
    become: yes

  - name: Install OS-level Python dependencies
    pip: name={{ item }} state=latest
    with_items:
      - pip
      - wheel
      - mysqlclient  # Required for Ansible mysql_db and mysql_user module
    become: yes

  - name: Create a new MariaDB database
    mysql_db:
      name: "{{ item }}"
      encoding: utf8
      state: "present"
    become: yes
    items: "{{ db_names }}"

  - name: Create a new MariaDB user
    mysql_user:
      name: "{{ db_user }}"
      password: "{{ db_pass }}"
      host: "localhost"
      priv: '*.*:ALL'
      state: present
    become: yes

  - name: Flush privileges
    command: mysql -e "FLUSH PRIVILEGES;"
    become: yes

  - name: Ensure virtualenv is initialized
    command: virtualenv {{ env_path }} -p {{virtualenv_python}}
    args:
      creates: "{{ env_path }}/bin/python"

  - name: Ensure requirements installed
    pip:
      requirements: "{{requirements_path}}"
      executable: "{{ env_path }}/bin/pip"

  - name: Update activator
    lineinfile:
      dest: "{{ env_path }}/bin/activate"
      state: present
      regexp: '^export {{ item.key }}='
      line: 'export {{ item.key }}="{{ item.value }}"'
    with_dict: "{{ settings }}"

  - name: Update ~/.bashrc to autostart in project
    lineinfile:
      dest: "~/.bashrc"
      state: present
      regexp: '^{{ item }}$'
      line: '{{ item }}'
    with_items:
      - "source {{ env_path }}/bin/activate;"
      - "cd {{src_path }};"

  - name: execute database migrations
    django_manage:
      command: migrate
      app_path: "{{ src_path }}"
      virtualenv: "{{ env_path }}"
    environment: "{{ settings }}"
